### ISSUE TITLE
Meteor 3 & v4

### ISSUE THREAD

**Issue by StorytellerCZ** [Meteor-Community-Packages/meteor-desktop#41]
Now that Meteor 3 is out and replacement for this package is still in the discussion phase, I think it might be worth it for interested people to start discussion and work on meteor-desktop v4 that would start with migration to Meteor 3, upgrade of electron to the latest compatible version with Node 20 and probably should not miss #15 (took a dig at it in #40).

Thoughts? Volunteers?

**Comment by a4xrbj1** [comment]
Sorry, only saw this now (I brought this up in the TypeScript issue).

I think this is a great plan to go ahead and I’m happy to test any RC/Beta version on my end (once it’s Meteor 3.x compatible).

But yes, we need to catch up to the many versions that ElectronJS is ahead.

**Comment by awatson1978** [comment]
Hi....
I'm probably going to take a stab at this, as I have a new project that has desktop support as a requirement.  Not going to be able to get to it until October.  But I've gotten the hang of refactoring from Fibers to ES6 async/await, and this isn't looking too terribly difficult.  

/me volunteers

**Comment by awatson1978** [comment]
Disclaimer:  No promises on Typescript support or Node 20 though.  

Maybe let's think about `meteor-desktop@3.1.0` that just replaces Fibers with ES6 async/await?

**Comment by awatson1978** [comment]
Okay, refactoring the to async/await syntax was actually pretty straight forward.  The dilemma is that the command line utility is trying to force the `communitypackages:meteor-desktop-watcher` and `communitypackages:meteor-desktop-bundler` packages at a specific version.  So we need to publish the atmosphere packages, then update the command line utility, then publish a new version of `meteor-desktop`.

## Todo
- [x] Publish the atmosphere packages.
- [x] Verify that compiler chain works and creates desktop app.
- [x] Publish the NPM utility.

**Comment by awatson1978** [comment]
<img width="1220" alt="Screenshot 2024-09-14 at 1 16 30 PM" src="https://github.com/user-attachments/assets/21227433-5990-4ed8-bda4-ef4dc0af3e9e">

**Comment by StorytellerCZ** [comment]
Awesome! I'll get around on publishing this now and then we can proceed on other things. Right now just the Fibers removal, no Meteor 3 support or anything else. One step at a time.

**Comment by StorytellerCZ** [comment]
@awatson1978 got this warning when publishing. Not an issue now, but needs to be fixed before moving to Meteor 3.
![image](https://github.com/user-attachments/assets/bd444a40-1ffb-4e75-b9f8-56a7a9265aa9)

**Comment by StorytellerCZ** [comment]
@awatson1978 everything seems to be working now. How would you like to proceed now?

**Comment by a4xrbj1** [comment]
> @awatson1978 everything seems to be working now. How would you like to proceed now?

Is there a RC out that I can try out, @StorytellerCZ ? Will probably have to build and deploy a new version of our app in the next 6h or so.

**Comment by StorytellerCZ** [comment]
The latest version has all the changes.

**Comment by awatson1978** [comment]
Hi!  I'll try to give it a test later today!

**Comment by awatson1978** [comment]
Hmmm...  I'm still getting dependency version errors.  I've been trying to trace where the version packages are specified, but haven't been able to track it down yet.

<img width="1046" alt="Screenshot 2024-09-17 at 9 50 18 PM" src="https://github.com/user-attachments/assets/144c8118-9c8a-47a1-89fd-d675698de7fa">

**Comment by msavin** [comment]
I just set up a new Meteor 3 / Blaze app and followed the set up steps... got this error:

```
=> App running at: http://localhost:3000/
=> Errors prevented startup:                  
   
   While loading plugin `meteor-desktop-bundler` from package `communitypackages:meteor-desktop-bundler`:
   packages/modules-runtime.js:222:12: Cannot find module 'fibers'
   at makeMissingError (packages/modules-runtime.js:222:12)
   at Module.require (packages/modules-runtime.js:241:17)
   at require (packages/modules-runtime.js:258:21)
   at module (packages/promise.js:40:3)
   at fileEvaluate (packages/modules-runtime.js:336:7)
   at Module.require (packages/modules-runtime.js:238:14)
   at require (packages/modules-runtime.js:258:21)
   at packages/promise.js:147:15
   at packages/promise.js:154:3
   
   
=> Your application has errors. Waiting for file change.
```

**Comment by awatson1978** [comment]
Gave it another try today with a fresh installation, using `npm run desktop`.
Received the following error, involving `omega:meteor-desktop-bundler@2.2.5`

![Image](https://github.com/user-attachments/assets/a41e1083-6b47-4ccb-ad52-835c1d1c4aec)

**Comment by awatson1978** [comment]
Gave it a try again, and am no longer getting my previous error, but am now getting the same error as Max.
![Image](https://github.com/user-attachments/assets/5043ea69-501e-4540-9547-71e0946eb590)

**Comment by ferjep** [comment]
Any update on this Meteor 3 support? It's pretty stable now

**Comment by awatson1978** [comment]
I just gave the install another try.  Same error as in October:

```
=> App running at: http://localhost:3000/
=> Errors prevented startup:                  
   
   While loading plugin `meteor-desktop-bundler` from package `communitypackages:meteor-desktop-bundler`:
   packages/modules-runtime.js:222:12: Cannot find module 'fibers'
   at makeMissingError (packages/modules-runtime.js:222:12)
   at Module.require (packages/modules-runtime.js:241:17)
   at require (packages/modules-runtime.js:258:21)
   at module (packages/promise.js:40:3)
   at fileEvaluate (packages/modules-runtime.js:336:7)
   at Module.require (packages/modules-runtime.js:238:14)
   at require (packages/modules-runtime.js:258:21)
   at packages/promise.js:147:15
   at packages/promise.js:154:3
   
   
=> Your application has errors. Waiting for file change.
```

It's installing the following packages, which is good.  That seems to resolve the issues in ticket #42.  

```
communitypackages:meteor-desktop-bundler@3.3.0
communitypackages:meteor-desktop-watcher@3.3.0
```

**Comment by awatson1978** [comment]
Per Claude:

### The Core Issue
The meteor-desktop-bundler plugin is trying to use fibers, which is no longer available in Meteor 3. Looking at the plugins in the codebase:

1. The issue is in the build plugin system of plugins/bundler/bundler.js and plugins/watcher/watcher.js, which still assume a Fibers-based environment. 
2. The most critical part is the Plugin.registerCompiler method that tries to process files with specific extensions. This was previously synchronous with Fibers, but now needs to be asynchronous.

### Suggested Fixes
Here's what needs to be updated:

1. Update the bundler.js processFilesForTarget method:
This method needs to be modified to use async/await instead of relying on Fibers for synchronous operations. The method currently contains synchronous code that would have been wrapped in Fibers in Meteor 2.x.

2. Update package.js files:
Both plugins/bundler/package.js and plugins/watcher/package.js need to be updated to indicate compatibility with Meteor 3 and remove any Fibers dependencies.

3. Update the Promise handling:
There are places in the code where Promise-based code is written assuming a Fibers environment. These need to be converted to proper async/await patterns.

4. Check meteor dependencies:
The plugin currently depends on older Meteor versions: api.versionsFrom('1.4.4.6'); in both plugins needs to be updated to match Meteor 3.x.

### Specific Changes Needed

1. In `plugins/bundler/package.js` and `plugins/watcher/package.js`, update:
```js
api.versionsFrom('METEOR@1.4.4.6');
```
to

```js
api.versionsFrom('METEOR@3.0');
```

2. In `plugins/bundler/bundler.js`, the `processFilesForTarget` method needs to be made async:

```js
javascriptCopyasync processFilesForTarget(files) {
    // existing code with async/await modifications
}
```

3. In `plugins/bundler/bundler.js`, update any calls to synchronous methods to use await:

```js
// Before
fs.readFileSync(...);

// After
await fs.promises.readFile(...);
```

4. The Plugin registration in `plugins/bundler/bundler.js` needs to be updated to handle the async nature:
```js
Plugin.registerCompiler(
    { extensions: ['desktop', '_desktop_.js'] },
    () => new MeteorDesktopBundler(Plugin.fs)
);
```

5. Similarly, update the watcher plugin to use async/await instead of relying on synchronous file operations.

**Comment by awatson1978** [comment]
Tested on a [second app](https://clinical-meteor.github.io/checklist-manifesto-3/).  Feel free to download the desktop app (for Mac) and give it a run.  

Have staged another PR with more bugfixes:
https://github.com/Meteor-Community-Packages/meteor-desktop/pull/48

**Comment by rrtkh** [comment]
Hello, what is current status of adjusting it to Meteor V3? I tested 4.0.0-rc.0 on windows but I'am getting fibers issue in bundled meteor package. I noticed in repository there is version rc.1 with commit message "it compiles to desktop! 4.0.0-rc.1" which looks promising, are there any plans to continue working on that?

**Comment by a4xrbj1** [comment]
> Hello, what is current status of adjusting it to Meteor V3? I tested 4.0.0-rc.0 on windows but I'am getting fibers issue in bundled meteor package. I noticed in repository there is version rc.1 with commit message "it compiles to desktop! 4.0.0-rc.1" which looks promising, are there any plans to continue working on that?

I've forked this package and upgrade `meteor-desktop` to the most modern JS technology, updated to latest ElectronJS versions and updated packages to fix security issues. Please note that my fork will only work with MeteorJS version 3.4 upwards:

[Build a Meteor's desktop client with hot code push.](https://github.com/a4xrbj1/meteor-desktop)
